name: Update Hackathon Registration Challenges
on:
  push:
    paths:
      - 'content/en/community/hackathons/sessions/registration-challenges/work/**/*'
jobs:
  resources:
    name: Update resources
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1

      - name: Fetch resources
        run: ./scripts/update_reg_challenges.sh

      - name: Update resources
        uses: peter-evans/create-pull-request@v5
        with:
          add-paths: static/assets/files/hackathon-registration.zip
          commit-message: 'hackathons: Update registration challenges'
          signoff: true
          delete-branch: true
          branch: bot/update-hack-registration
          base: main
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'Update hackathon registration challenges'
